siabsen/app/routes.php
<?php

# CSRF Protection
Route::when('*', 'csrf', ['POST', 'PUT', 'PATCH', 'DELETE']);

# Static Pages. Redirecting admin so admin cannot access these pages.
Route::group(['before' => 'redirectAdmin'], function()
{
	Route::get('/', ['as' => 'home', 'uses' => 'PagesController@getHome']);
	Route::get('/about', ['as' => 'about', 'uses' => 'PagesController@getAbout']);
	Route::get('/contact', ['as' => 'contact', 'uses' => 'PagesController@getContact']);
});

# Registration
Route::group(['before' => 'guest'], function()
{
	Route::get('/register', 'RegistrationController@create');
	Route::post('/register', ['as' => 'registration.store', 'uses' => 'RegistrationController@store']);
});

# Authentication
Route::get('login', ['as' => 'login', 'uses' => 'SessionsController@create'])->before('guest');
Route::get('logout', ['as' => 'logout', 'uses' => 'SessionsController@destroy']);
Route::resource('sessions', 'SessionsController' , ['only' => ['create','store','destroy']]);

# Forgotten Password
Route::group(['before' => 'guest'], function()
{
	Route::get('forgot_password', 'RemindersController@getRemind');
	Route::post('forgot_password','RemindersController@postRemind');
	Route::get('reset_password/{token}', 'RemindersController@getReset');
	Route::post('reset_password/{token}', 'RemindersController@postReset');
});


# Standard User Routes
Route::group(['before' => 'auth|standardUser'], function()
{
	Route::get('userProtected', 'StandardUserController@getUserProtected');
	Route::resource('profiles', 'UsersController', ['only' => ['show', 'edit', 'update']]);


});

# Admin Routes
Route::group(['before' => 'auth|admin'], function()
{
	Route::get('/admin', ['as' => 'admin_dashboard', 'uses' => 'AdminController@getHome']);
    Route::resource('admin/profiles', 'AdminUsersController', ['only' => ['index', 'show', 'create', 'store', 'edit', 'update']]);
 	Route::get('admin/profiles/destroy/{id}','AdminUsersController@destroy');
 	Route::get('admin/profiles/reset/{id}','AdminUsersController@resetPass');
 	Route::get('admin/mesin/destroy/{id}','AdminMesinController@destroy');
 	Route::get('admin/holiday/destroy/{id}','AdminHolidayController@destroy');
 	Route::get('admin/jamkerja/destroy/{id}','AdminJamController@destroy');
 	Route::get('admin/shift/destroy/{id}','AdminShiftController@destroy');
 	Route::get('admin/jadwal/destroy/{id}','AdminJadwalController@destroy');
 	Route::resource('admin/group', 'AdminGroupController', ['only' => ['index','create', 'store', 'edit', 'update', 'destroy']]); 
	Route::resource('admin/mesin', 'AdminMesinController', ['only' => ['index','create', 'store', 'edit', 'update', 'destroy']]); 
	Route::resource('admin/holiday', 'AdminHolidayController', ['only' => ['index','create', 'store', 'edit', 'update', 'destroy']]);
	Route::resource('admin/jamkerja', 'AdminJamController', ['only' => ['index','create', 'store', 'edit', 'update', 'destroy']]); 
 	Route::resource('admin/shift', 'AdminShiftController', ['only' => ['index','create', 'store', 'edit', 'update', 'destroy']]);
 	Route::resource('admin/jadwal', 'AdminJadwalController', ['only' => ['index','create', 'store', 'edit', 'update', 'destroy']]);
});

siabsen/app/views/protected/admin/admin_dashboard.blade.php
@extends('protected.admin.master')

@section('title', 'Admin Dashboard')

@section('content')

	@if (Session::has('flash_message'))
			<p>{{ Session::get('flash_message') }}</p>
	@endif


	<div class="jumbotron">
		<h1>Admin Page</h1>
		<p>This page is for admins only!</p>
	</div>


@stop

siabsen/app/views/protected/admin/create.blade.php
@extends('protected.admin.master')

@section('title', 'Tambah User')

@section('content')
	<h1>Form Tambah User</h1>
    
@if (Session::has('flash_message'))
		<div class="form-group">
			<p style="padding: 5px" class="bg-success">{{ Session::get('flash_message') }}</p>
		</div>
	@endif
	<div class="col-md-8">
	{{ Form::open(['route' => 'admin.profiles.store']) }}

				<!-- Email field -->
							<div class="form-group">
								{{ Form::text('email', null, ['placeholder' => 'Email', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('email', $errors) }}
							</div>

							<!-- Password field -->
							<div class="form-group">
							{{ Form::password('password', ['placeholder' => 'Password', 'class' => 'form-control', 'required' => 'required'])}}
							{{ errors_for('password', $errors) }}
							</div>

							<!-- Password Confirmation field -->
							<div class="form-group">
							{{ Form::password('password_confirmation', ['placeholder' => 'Password Confirm', 'class' => 'form-control', 'required' => 'required'])}}

							</div>

							<!-- First name field -->
							<div class="form-group">
								{{ Form::text('first_name', null, ['placeholder' => 'First Name', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('first_name', $errors) }}
							</div>

							<!-- Last name field -->
							<div class="form-group">
								{{ Form::text('last_name', null, ['placeholder' => 'Last Name', 'class' => 'form-control', 'required' => 'required'])}}
								{{ errors_for('last_name', $errors) }}
							</div>
                            
                            <div class="form-group">
							{{ Form::label('account_type', 'Account Type:') }}
							{{ Form::select('account_type', $groups, ['class' => 'form-control']) }}
							{{ errors_for('account_type', $errors) }}
							</div>
            
            {{ Form::submit('SIMPAN', array('class' => 'btn btn-lg btn-primary btn-block')) }}
        {{ Form::close() }}
 
    </div>
@stop

siabsen/app/views/protected/admin/edit_user.blade.php
@extends('protected.admin.master')

@section('title', 'Edit Profile')

@section('content')
	<h1>Edit Profile</h1>

	@if (Session::has('flash_message'))
		<div class="form-group">
			<p style="padding: 5px" class="bg-success">{{ Session::get('flash_message') }}</p>
		</div>
	@endif

	{{ Form::model($user, ['method' => 'PATCH', 'route' => ['admin.profiles.update', $user->id]]) }}

		<div class="form-group">
			{{ Form::label('account_type', 'Account Type:') }}
			{{ Form::select('account_type', $groups, $user_group, ['class' => 'form-control']) }}
			{{ errors_for('account_type', $errors) }}
		</div>

		<!-- email Field -->
		<div class="form-group">
			{{ Form::label('email', 'Email:') }}
			{{ Form::email('email', null, ['class' => 'form-control']) }}
			{{ errors_for('email', $errors) }}
		</div>


		<!-- first_name Field -->
		<div class="form-group">
			{{ Form::label('first_name', 'First Name:') }}
			{{ Form::text('first_name', null, ['class' => 'form-control']) }}
			{{ errors_for('first_name', $errors) }}
		</div>

		<!-- last_name Field -->
		<div class="form-group">
			{{ Form::label('last_name', 'Last Name:') }}
			{{ Form::text('last_name', null, ['class' => 'form-control']) }}
			{{ errors_for('last_name', $errors) }}

		</div>

		<!-- Password field -->
		<div class="form-group">
			{{ Form::label('password', 'Password:') }}
			{{ Form::password('password', ['class' => 'form-control']) }}
			<p class="help-block">Leave password blank to NOT edit the password.</p>
			{{ errors_for('password', $errors) }}
		</div>

		<!-- Password Confirmation field -->
		<div class="form-group">
			{{ Form::label('password_confirmation', 'Repeat Password:') }}
			{{ Form::password('password_confirmation', ['class' => 'form-control'] )}}
		</div>


		<!-- Update Profile Field -->
		<div class="form-group">
			{{ Form::submit('Update Profile', ['class' => 'btn btn-primary']) }}
		</div>
	{{ Form::close() }}

@stop

siabsen/app/views/protected/admin/list_users.blade.php
@extends('protected.admin.master')

@section('title', 'List Users')

@section('content')
@if (Session::has('flash_message'))
		<div class="form-group">
			<p style="padding: 5px" class="bg-success">{{ Session::get('flash_message') }}</p>
		</div>
	@endif
<h2>Daftar Karyawan</h2>
	<div class="col-md-2">
    <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#newuser" data-tooltip="tooltip" data-placement="top" title="Tambah User"><i class="fa fa-user-plus fa-lg"></i></button>
	<br>
	</div>
	<table class="table table-bordered table-striped table-hover">
		<thead>
	        <tr>
	          <th>Akses</th>
	          <th>Email</th>
	          <th>First Name</th>
	          <th>Last Name</th>
	          <th>Action</th>
	        </tr>
      	</thead>

      	<tbody>
      		@foreach ($users as $user)
      		<tr>
	      		<td>
	      			@if($user->inGroup($admin))
	      			<span class="label label-success" data-tooltip="tooltip" data-placement="top" title="{{$user->first_name}} is admin">{{ 'Admin' }}</span>
	      			@else
	      			<span class="label label-info" data-tooltip="tooltip" data-placement="top" title="{{$user->first_name}} is ordinary user">{{ 'User' }}</span>
	      			@endif
	      		</td>
		        <td>{{ link_to_route('admin.profiles.show', $user->email, $user->id) }}
		        </td>
		        <td>{{ $user->first_name}}</td>
		        <td>{{ $user->last_name}}</td>
		        <td>
		        	<div class="btn-group">
			        <button type="button" class="btn btn-warning" data-toggle="modal" data-tooltip="tooltip"  data-target="{{'#editmodal'}}{{$user->id}}" data-placement="top" title="Edit"><span class="glyphicon glyphicon-pencil" aria-hidden="true" ></span></button>
					@include('includes.edit')
					<button type="button" class="btn btn-danger" data-toggle="modal" data-target="{{'#delete'}}{{$user->id}}" data-tooltip="tooltip" data-placement="top" title="Hapus"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
					@include('includes.delete')
					<a href={{ URL::to('admin/profiles/reset/'.$user->id) }}><button type="button" class="btn btn-active" data-tooltip="tooltip" data-placement="top" title="Reset Password"><span class="glyphicon glyphicon-repeat" aria-hidden="true"></span></button></a>
		        	</div>
		        </td>
		     </tr>

			@endforeach
			
      	</tbody>
	</table>
	@include('includes.create')

@stop

siabsen/app/views/protected/admin/master.blade.php
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="utf-8">
	<title>@yield('title') - Admin - SI Absensi</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- Stylesheets -->
	{{ HTML::style('assets/css/bootstrap.min.css') }}
	{{ HTML::style('assets/font-awesome-4.3.0/css/font-awesome.min.css') }}
	{{ HTML::style('assets/css/sweet-alert.css') }}

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<!--Js config-->
	{{ HTML::script('assets/js/jquery-1.11.0.js') }}
	{{ HTML::script('assets/js/bootstrap.min.js') }}
	{{ HTML::script('assets/js/sweet-alert.js') }}
	<script type="text/javascript">
    $(function () {$('[data-tooltip="tooltip"]').tooltip()});
    $('#myModal').on('shown.bs.modal', function () {
    $('#myInput').focus()});
  	</script>
</head>
<body>

	<header>

		<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="/">Signed as Admin</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li class="{{ set_active_admin('admin') }}"><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a></li>
		      </ul>

		      <ul class="nav navbar-nav navbar-right">

		        <li><a href="/logout"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>Logout</a></li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
	</header>
	@include('includes.sidebar')

	<div class="container col-md-offset-2 col-md-10">
		@yield('content')
	</div>
</body>
</html>

siabsen/app/views/protected/admin/show_user.blade.php
@extends('protected.admin.master')

@section('title', 'View Profile')

@section('content')

	<h1>{{ $user->first_name }}'s Profile</h1>
	<ul>
		<li>Account Type: {{ $user_group }}</li>
		<li>Email Address: {{ $user->email }}</li>
		<li>First Name: {{ $user->first_name }}</li>
		<li>Last Name: {{ $user->last_name }}</li>
	</ul>

	@if(Sentry::check())

		{{ link_to_route('admin.profiles.edit', 'Edit Profile', $user->id, ['class' => 'btn btn-primary']) }}

	@endif

@stop